### ISSUE TITLE
Favorite Devices is empty on Kobo Glo HD

### ISSUE THREAD

**Issue by rhannink** [athombv/homey.ink#13]
Hi,

I just tried to Install Homey.ink on a Kobo Glo HD. If I follow your guide, everything seems to work, I get the dashboard, the Temperature and the time/date is displayed ok, but the Favorite Devices are empty. In the Homey app I have 2 favourite devices.

When I now add new favourite Devices in the app, they do show up on the ink display. So exsisting Favourite Devices do not show up, just Newly added ones.

Everything else works pretty good on the Kobo Glo HD, Only a verticaal line to the right of the screen I can't get did off.

Gr. Remco

**Comment by caseda** [comment]
Only toggle able devices will show up (on/off, play/pause), so if those 2 are for example a thermostat, they will not show up.

**Comment by WeeJeWel** [comment]
Probably what @caseda said!
