### ISSUE TITLE
Cannot get this to work with Homey 7.2.1

### ISSUE THREAD

**Issue by azurit** [athombv/homey.ink#32]
Hi,

is homey.ink still suppose to work with Homey 7.2.1? I cannot get it to work - dashboard has no values like with invalid token (i tried it about 100x times with different tokens).

**Comment by azurit** [comment]
Even https://app.homey.ink/ doesn't work (after logging in on main domain).

**Comment by WeeJeWel** [comment]
Works fine here. Do you have more information?

**Comment by azurit** [comment]
What information do you need?

**Comment by azurit** [comment]
I'm trying also local version with URL:
`http://localhost:5000/?theme=web&token=access_token`

I'm getting token from a homey.ink page from a JSON response:
`{"token_type":"bearer","access_token":"<censored>","expires_in":3660,"refresh_token":"<censored>"}`

Result:
![homeyink](https://user-images.githubusercontent.com/1083063/152644886-991bcc4e-4023-435b-8017-0c551c333d72.png)

**Comment by WeeJeWel** [comment]
That's good. Any console errors?

**Comment by azurit** [comment]
I see this:
![homeyink2](https://user-images.githubusercontent.com/1083063/152645028-d12d4410-ba7e-4221-b60f-a070e8e7574d.png)

**Comment by azurit** [comment]
Firefox 96.0 on Kubuntu linux.

**Comment by WeeJeWel** [comment]
Seems like you missed a character(s) while copy/pasting.

**Comment by azurit** [comment]
Copy/pasting of what? Token?

**Comment by azurit** [comment]
I uploaded a screenshot of console error, if you meant this.

**Comment by azurit** [comment]
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    <anonymous> http://localhost:5000/js/homey.ink.app.js:40
    EventListener.handleEvent* http://localhost:5000/js/homey.ink.app.js:4
```

**Comment by azurit** [comment]
I was able to make it work with this:
 - commenting out line 39 in `app/js/homey.ink.app.js` (`token = atob(token);`)
 - pasting the whole JSON response (not only value of `access_token`) to the `token` parameter:
`http://localhost:5000/?theme=web&token={%22token_type%22:%22bearer%22,%22access_token%22:%22<censored>%22,%22expires_in%22:3660,%22refresh_token%22:%22<censored>%22}`

**Comment by WeeJeWel** [comment]
No idea what the issue is, so until someone else finds that out, I can't fix it :)
