### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by oskar1971** [athombv/homey.ink#33]
Hi!

When I change an icon on a unit in homey it does still show the original icon, for example the "Z" for a zigbee device or the dimmer for a nexa dimmer, in the homeydash.
Is that the way it is or am I doing something wrong?

Best regards and thax for the app!
Oskar

**Comment by oskar1971** [comment]
Just found out that if I use the "virtual devices" app in homey and create a virtual device, I can upload a icon from the web and that one will show!!!
See the two attached pictures, one is homeydash and the other the basic web page of my homey.

Bast regards
Oskar
<img width="701" alt="bild 1" src="https://user-images.githubusercontent.com/82240237/171842941-486cbe0e-a0f3-4a0e-9582-3352154d02cc.png">
<img width="626" alt="bild 2" src="https://user-images.githubusercontent.com/82240237/171843003-c8ff6a01-98e8-4e9f-9133-941ea1165d26.png">

**Comment by WeeJeWel** [comment]
Support for custom icons has been added!
