### ISSUE TITLE
Support for Advanced flows

### ISSUE THREAD

**Issue by Tukker2021** [athombv/homey.ink#34]
Are there any plans to support advanced flows in the favorites, as currently I have to work around this by creating a regular flow that starts the advanced flow?

**Comment by WeeJeWel** [comment]
I've added support for Advanced Flows!

**Comment by Tukker2021** [comment]
Hi Emiel, when will this update to homey.ink (Homeydash) will be available, as I still only see the regular flows and missing the advanced flows (see snapshot below)
![image](https://user-images.githubusercontent.com/88245214/180743320-a7e65e0b-b568-417d-bdf1-60b439999610.png)

**Comment by WeeJeWel** [comment]
It's already live. But what you're displaying is not homey.ink ..

**Comment by Tukker2021** [comment]
You are correct, but will these changes then not automatically be propagated to https://homeydash.com/ and https://dash.homeycornelisse.nl/, or should I submit an enhancement request to the creators of this variation of homey.ink?

**Comment by WeeJeWel** [comment]
> or should I submit an enhancement request to the creators of this variation of homey.ink?

I think so! I have no idea what they've done :)
