### ISSUE TITLE
Bring homey.ink to the Invisible Computers e-paper display?

### ISSUE THREAD

**Issue by KonstantinSchubert** [athombv/homey.ink#37]
Could we bring the homey.ink app to the e-paper display by Invisible Computers? 

https://shop.invisible-computers.com/products/invisible-calendar

This display is designed to look good on a living room wall or on a shelf, and I think that makes it a really good fit for a home monitoring application. 

However, the eink screen from Invisible Computers does not have a touch screen, since it is meant to be read-only. 

Does homey.ink require a touchscreen or does it also have a dashboard mode which gives an overview over the state of the home? 

I'd love to cooperate.

**Comment by WeeJeWel** [comment]
I don’t have one so… go ahead and make it useful :)
