### ISSUE TITLE
Problem loggin in.

### ISSUE THREAD

**Issue by AltonV** [athombv/homey.ink#38]
After logging in with my homey account and choosing allow the popup window is just sitting there, empty.
I have tested both Chromium and Firefox.
I'm not sure if it's relevant, but in the browser console, I get a different error depending on the browser.

Chromium
```
Uncaught TypeError: Cannot read properties of null (reading 'postMessage')
    at login.html?code=ab3c348630f1892240b876d1459d9f3785db3fce:4:15
```

Firefox
```
Uncaught TypeError: window.opener is null
    <anonymous> https://homey.ink/login.html?code=c193b269da4e2dc85923497d44ebeced2de94d09:4
```

**Comment by WeeJeWel** [comment]
Hm it does seem that browsers have dropped support for `window.opener`.

I've published a newer version which simply redirects the webpage instead.
